import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <title>Industry</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="shortcut icon" type="image/x-icon" href="assets/images/top-logo.svg" />
        <link rel="stylesheet" href="assets/css/vendor/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/css/vendor/animate.min.css" />
        <link rel="stylesheet" href="assets/css/plugins/swiper.min.css" />
        <link rel="stylesheet" href="assets/css/plugins/nice-select.css" />
        <link rel="stylesheet" href="assets/css/plugins/nouislider.min.css" />
        <link rel="stylesheet" href="assets/css/vendor/magnific-popup.css" />
        <link rel="stylesheet" href="assets/css/vendor/odometer.min.css" />
        <link rel="stylesheet" href="assets/css/vendor/fontawesome-pro.css" />
        <link rel="stylesheet" href="assets/css/vendor/spacing.css" />
        <link rel="stylesheet" href="assets/css/vendor/remixicon.css" />
        <link rel="stylesheet" href="assets/css/main.css" />

      </head>

      <body>
        {children}
      </body>
    </html>
  );
}
